name: Build

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B test --file pom.xml
      - name: Generate Javadoc
        run: |
          mvn -B test javadoc:aggregate --file pom.xml
          mkdir javadoc
          cd javadoc
          git init
          git checkout -b apidocs
          cp -r ../target/site/apidocs/. ./
          git add .
          git -c user.name='CrissNamon' -c user.email='danilarassokhin@gmail.com' commit -am 'Update docs'
          git push -u origin apidocs --force &>/dev/null