name: Build

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Test
        run: mvn -B test
      - name: Generate Javadoc
        run: |
          mkdir compaj-docs
          mkdir compaj-docs/javadoc
          cd compaj-docs
          mvn -B javadoc:aggregate --file pom.xml
          cp -r ../target/site/apidocs/. ./javadoc/
          git fetch origin apidocs:apidocs
          git checkout apidocs
          git add .
          git -c user.name='travis' -c user.email='travis' commit -m 'Update docs'
          git push