name: Build

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Generate Javadoc
        run: |
          mvn -B test javadoc:aggregate --file pom.xml
          mkdir compaj-docs
          mkdir compaj-docs/javadoc
          cd compaj-docs
          git init
          git checkout -b apidocs
          git pull https://github.com/CrissNamon/compaj.git apidocs
          cp -r ../target/site/apidocs/. ./javadoc/
          git add .
          git -c user.name='travis' -c user.email='travis' commit -m 'Update docs'
          git remote add origin https://github.com/CrissNamon/compaj.git
          git remote -v
          git push -u origin apidocs