name: Javadoc

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Generate Javadoc
        run: |
          mvn -B -DskipTests javadoc:aggregate --file pom.xml
          mkdir apidocs
          mkdir apidocs/docs
          mkdir apidocs/docs/javadoc
          cp -r ./target/site/apidocs/. ./apidocs/docs/javadoc/
          cp -r .git ./apidocs/
          cp -r .gitignore ./apidocs/.gitignore
          cd apidocs
          git branch -M apidocs
          git add .
          git -c user.name='HiddenProject' -c user.email='danilarassokhin@gmail.com' commit -m 'Update docs'
          git push -u origin apidocs --force
