name: Javadoc

on:
  push:
    branches: [ "main", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Test
        run: mvn -B test --file pom.xml
      - name: Generate Javadoc
        run: |
          mvn -B -DskipTests javadoc:aggregate --file pom.xml
          mkdir docs
          mkdir docs/javadoc
          cp -r ./target/site/apidocs/. ./docs/javadoc/
          git add .
          git stash push
          git fetch origin apidocs
          git checkout apidocs
          rm -rf docs
          git stash pop
          git -c user.name='HiddenProject' -c user.email='danilarassokhin@gmail.com' commit -m 'Update docs'
          git push -u origin apidocs